---
- name: Install various applications on Ubuntu
  hosts: local
  become: yes
  gather_facts: yes # Ensures that ansible_distribution_release is available

  vars:
    NODEJS_VERSION: "20"

  tasks:
    # Update apt cache before adding repositories
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    # Import GPG keys for repositories
    - name: Import Microsoft GPG key for VSCode
      ansible.builtin.apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Import Google Chrome GPG key
      ansible.builtin.apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    # Add software repositories
    - name: Add VSCode repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/repos/code stable main"
        state: present
        filename: vscode
        update_cache: yes

    - name: Add Google Chrome repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
        state: present
        filename: google-chrome
        update_cache: yes

    # Add Node.js repository and GPG key in the recommended way
    - name: Install Node.js dependencies
      ansible.builtin.apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Ensure old NodeSource repository entries are removed
      ansible.builtin.lineinfile:
        path: "/etc/apt/sources.list.d/nodesource.list"
        state: absent
        regexp: "^deb https://deb.nodesource.com/node_"
        backrefs: yes
      become: yes

    - name: Add NodeSource GPG key
      ansible.builtin.apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add NodeSource repository
      ansible.builtin.apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_lsb.codename }} main"
        state: present
        filename: nodesource
        update_cache: yes

    # Install Visual Studio Code, Google Chrome, and Node.js
    - name: Install applications
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - code # VSCode
        - google-chrome-stable # Google Chrome
        - nodejs # Node.js

    # Check if Slack is installed and conditionally install
    - name: Check if Slack is installed
      ansible.builtin.shell:
        cmd: "dpkg-query -W -f='${Status}' slack-desktop || true"
      register: slack_installed
      changed_when: false
      failed_when: false
      ignore_errors: true

    - name: Download Slack .deb package
      ansible.builtin.get_url:
        url: https://downloads.slack-edge.com/releases/linux/4.36.2/prod/x64/slack-desktop-4.36.2-amd64.deb
        dest: "/tmp/slack-desktop.deb"
      when: slack_installed.stdout is defined and slack_installed.stdout == "0"

    - name: Install Slack from downloaded .deb package
      ansible.builtin.apt:
        deb: /tmp/slack-desktop.deb
      when: slack_installed.stdout is defined and slack_installed.stdout == "0"

    # Postman Installation
    - name: Check if Postman is installed
      ansible.builtin.stat:
        path: /opt/Postman
      register: postman_installed

    - name: Ensure unzip is installed
      apt:
        name: unzip
        state: present

    - name: Download Postman
      get_url:
        url: "https://dl.pstmn.io/download/latest/linux64"
        dest: /tmp/postman-linux-x64.tar.gz

    - name: Extract Postman archive
      unarchive:
        src: /tmp/postman-linux-x64.tar.gz
        dest: /opt
        remote_src: yes

    - name: Create symlink for Postman executable
      file:
        src: /opt/Postman/Postman
        dest: /usr/local/bin/postman
        state: link

    - name: Create desktop shortcut for Postman
      template:
        src: postman.desktop.j2
        dest: /usr/share/applications/postman.desktop
